comments

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -56,7 +56,37 @@ jobs:
 
       - name: Lint
         run: make lint
+  check-nuctl-docs:
+    runs-on: ubuntu-latest
 
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          cache: true
+          go-version-file: go.mod
+
+      - name: Generate Nuctl docs
+        run: make generate-nuctl-docs
+
+      - name: Get Makefile Variable
+        id: get-nuctl-docs-path
+        run: echo "NUCTL_DOCUMENTATION_PATH=$(make print-nuctl-docs-path | tail -n 1)" >> $GITHUB_ENV
+
+      - name: Check Nuctl docs changes
+        run: |
+          if [[ -n $(git status ${{ env.NUCTL_DOCUMENTATION_PATH }}) ]]; then
+            echo "::error::Documentation needs to be regenerated. Please run 'make generate-nuctl-docs' and commit the changes."
+            echo "Differences between current and generated state:"
+            git diff ${{ env.NUCTL_DOCUMENTATION_PATH }}
+            exit 1
+          else
+            echo "No changes in nuctl documentation."
+          fi
+          
   check-copyright-license:
     name: Check copyright and license
     runs-on: ubuntu-latest
